//
// Created by 22855 on 24-4-10.
//

#ifndef VET6_AVOIDING_H
#define VET6_AVOIDING_H

#define LS_ON HAL_GPIO_ReadPin(LS_DS_BL_GPIO_Port,LS_DS_BL_Pin)==GPIO_PIN_RESET
#define LS_OFF HAL_GPIO_ReadPin(LS_DS_BL_GPIO_Port,LS_DS_BL_Pin)==GPIO_PIN_SET
#define RS_ON HAL_GPIO_ReadPin(RS_DS_BL_GPIO_Port,RS_DS_BL_Pin)==GPIO_PIN_RESET
#define RS_OFF HAL_GPIO_ReadPin(RS_DS_BL_GPIO_Port,RS_DS_BL_Pin)==GPIO_PIN_SET

#endif //VET6_AVOIDING_H
